version: '3.8'
services:
  appzip:
    # build: .
    image: registry.access.redhat.com/ubi9/python-312:latest
    container_name: i4c_container
    command: tail -f /dev/null
    volumes:
      - .:/app
