[tool.poetry]
name = "dicgc"
version = "0.1.0"
description = ""
authors = ["Gnanaprakasam <PENTA009@KVBMAIL.COM>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.115.6"
uvicorn = "^0.34.0"
passlib = "^1.7.4"
pyjwt = "^2.10.1"
python-dotenv = "^1.0.1"
sqlalchemy = "^2.0.36"
openpyxl = "^3.1.5"
pandas = "^2.2.3"
boto3 = "^1.35.94"
email-validator = "^2.2.0"
psycopg2 = "^2.9.10"
python-multipart = "^0.0.20"
pycryptodome = "^3.21.0"
requests = "^2.32.3"
curlify = "^2.2.1"
orjson = "^3.10.13"
sqlparse = "^0.5.3"
jinja2 = "^3.1.5"
brotli-asgi = "^1.4.0"
apscheduler = "^3.11.0"
pre-commit = "^4.1.0"
weasyprint = "^63.1"
num2words = "^0.5.14"
python-docx = "^1.1.2"
beautifulsoup4 = "^4.12.3"
pdfplumber = "^0.11.5"
pypandoc = "^1.15"
cx-oracle = "^8.3.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
